spring.application.name=bank

spring.security.user.name=admin
spring.security.user.password=admin

spring.datasource.url=jdbc:postgresql://localhost:5432/mybank
spring.datasource.username=psql
spring.datasource.password=mySecretKey

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=mysupersecurelongsecretkeyformacalgorithm
refresh.secret=vE6RHCh9hOXgN7TZh0HCAz9KP+vK3s1ZNVmIRdJMI/byewxi

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=micro-1

management.endpoints.web.exposure.include=prometheus