spring.application.name=email-svc
server.port=9090

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=q vhshbqsbjqn
spring.mail.password=xxxxxxxxxxx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.kafka.bootstrap-server=localhost:9092